# Generated by Django 3.1 on 2020-09-24 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.courses'),
        ),
        migrations.AddField(
            model_name='resources',
            name='sem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.semesters'),
        ),
    ]
