# Generated by Django 3.1 on 2020-09-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200924_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesters',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
