# Generated by Django 3.1 on 2020-09-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200924_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=20)),
                ('resource', models.TextField()),
            ],
        ),
    ]
