# Generated by Django 3.1 on 2020-10-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20201009_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
