# Generated by Django 3.1 on 2020-10-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20201010_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='feedback',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
