# Generated by Django 3.1 on 2020-10-13 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20201010_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.semesters')),
            ],
        ),
        migrations.AlterField(
            model_name='resources',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subject'),
        ),
    ]
