# Generated by Django 3.1 on 2020-10-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20201013_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
